/**
 * Version information for wumpus-sharpee
 * Auto-generated by sharpee - DO NOT EDIT
 */
export const STORY_VERSION = '0.3.2';
export const BUILD_DATE = '2026-09-15T16:04:57Z';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE } as const;
