/**
 * Version information for wumpus-sharpee
 * Auto-generated by sharpee - DO NOT EDIT
 */
export const STORY_VERSION = '0.3.1';
export const BUILD_DATE = '2026-09-11T10:17:18Z';
export const ENGINE_VERSION = '5.0.0';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE, engineVersion: ENGINE_VERSION } as const;
